identity:
  author: YoFoon
  name: mcp_config
  label:
    en_US: MCP Config During Use
    zh_Hans: 使用时配置的MCP工具
  description:
    en_US: Fetch and call tools by MCP protocol through HTTP with SSE transport or Streamable HTTP transport, configuring during use.
    zh_Hans: 通过HTTP with SSE传输或Streamable HTTP传输使用MCP协议来发现和调用工具，使用时配置。
  icon: icon.svg
  tags:
    - utilities
tools:
  - tools/mcp_list_tools.yaml
  - tools/mcp_call_tool.yaml
extra:
  python:
    source: provider/mcp_config.py 